ALTER TABLE IF EXISTS "accounts" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE IF EXISTS "sessions" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE IF EXISTS "users" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
ALTER TABLE IF EXISTS "verifications" DISABLE ROW LEVEL SECURITY;--> statement-breakpoint
DROP TABLE IF EXISTS "accounts" CASCADE;--> statement-breakpoint
DROP TABLE IF EXISTS "sessions" CASCADE;--> statement-breakpoint
DROP TABLE IF EXISTS "users" CASCADE;--> statement-breakpoint
DROP TABLE IF EXISTS "verifications" CASCADE;--> statement-breakpoint
ALTER TABLE "user_profiles" ADD COLUMN "role" "user_role" DEFAULT 'Supervisor' NOT NULL;--> statement-breakpoint
ALTER TABLE "custom_labour_types" ADD CONSTRAINT "custom_labour_types_created_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_labour_types" ADD CONSTRAINT "custom_labour_types_updated_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_machinery_types" ADD CONSTRAINT "custom_machinery_types_created_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_machinery_types" ADD CONSTRAINT "custom_machinery_types_updated_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_material_types" ADD CONSTRAINT "custom_material_types_created_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_material_types" ADD CONSTRAINT "custom_material_types_updated_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_units" ADD CONSTRAINT "custom_units_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_units" ADD CONSTRAINT "custom_units_created_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "custom_units" ADD CONSTRAINT "custom_units_updated_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_entries" ADD CONSTRAINT "expense_entries_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "expense_entries" ADD CONSTRAINT "expense_entries_created_by_user_profiles_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "field_definitions" ADD CONSTRAINT "field_definitions_subcategory_id_subcategories_subcategory_id_fk" FOREIGN KEY ("subcategory_id") REFERENCES "public"."subcategories"("subcategory_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "field_requests" ADD CONSTRAINT "field_requests_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "field_requests" ADD CONSTRAINT "field_requests_category_id_categories_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("category_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "field_requests" ADD CONSTRAINT "field_requests_subcategory_id_subcategories_subcategory_id_fk" FOREIGN KEY ("subcategory_id") REFERENCES "public"."subcategories"("subcategory_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "field_requests" ADD CONSTRAINT "field_requests_requested_by_user_profiles_user_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generic_entries" ADD CONSTRAINT "generic_entries_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generic_entries" ADD CONSTRAINT "generic_entries_field_definition_id_field_definitions_field_definition_id_fk" FOREIGN KEY ("field_definition_id") REFERENCES "public"."field_definitions"("field_definition_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "generic_entries" ADD CONSTRAINT "generic_entries_created_by_user_profiles_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incident_reports" ADD CONSTRAINT "incident_reports_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incident_reports" ADD CONSTRAINT "incident_reports_reported_by_user_profiles_user_id_fk" FOREIGN KEY ("reported_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "labour_entries" ADD CONSTRAINT "labour_entries_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "labour_entries" ADD CONSTRAINT "labour_entries_work_type_custom_id_custom_labour_types_labour_type_id_fk" FOREIGN KEY ("work_type_custom_id") REFERENCES "public"."custom_labour_types"("labour_type_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "labour_entries" ADD CONSTRAINT "labour_entries_created_by_user_profiles_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "machinery_entries" ADD CONSTRAINT "machinery_entries_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "machinery_entries" ADD CONSTRAINT "machinery_entries_equipment_type_custom_id_custom_machinery_types_equipment_type_id_fk" FOREIGN KEY ("equipment_type_custom_id") REFERENCES "public"."custom_machinery_types"("equipment_type_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "machinery_entries" ADD CONSTRAINT "machinery_entries_created_by_user_profiles_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_entries" ADD CONSTRAINT "material_entries_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_entries" ADD CONSTRAINT "material_entries_material_type_custom_id_custom_material_types_material_type_id_fk" FOREIGN KEY ("material_type_custom_id") REFERENCES "public"."custom_material_types"("material_type_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_entries" ADD CONSTRAINT "material_entries_unit_master_id_unit_master_unit_id_fk" FOREIGN KEY ("unit_master_id") REFERENCES "public"."unit_master"("unit_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_entries" ADD CONSTRAINT "material_entries_unit_custom_id_custom_units_unit_id_fk" FOREIGN KEY ("unit_custom_id") REFERENCES "public"."custom_units"("unit_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "material_entries" ADD CONSTRAINT "material_entries_created_by_user_profiles_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "notifications" ADD CONSTRAINT "notifications_user_id_user_profiles_user_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_requests" ADD CONSTRAINT "resource_requests_site_id_sites_site_id_fk" FOREIGN KEY ("site_id") REFERENCES "public"."sites"("site_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_requests" ADD CONSTRAINT "resource_requests_requested_by_user_profiles_user_id_fk" FOREIGN KEY ("requested_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_requests" ADD CONSTRAINT "resource_requests_approved_by_user_profiles_user_id_fk" FOREIGN KEY ("approved_by") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_from_site_id_sites_site_id_fk" FOREIGN KEY ("from_site_id") REFERENCES "public"."sites"("site_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_to_site_id_sites_site_id_fk" FOREIGN KEY ("to_site_id") REFERENCES "public"."sites"("site_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_requested_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("requested_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_approved_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("approved_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_work_type_custom_id_custom_labour_types_labour_type_id_fk" FOREIGN KEY ("work_type_custom_id") REFERENCES "public"."custom_labour_types"("labour_type_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_material_type_custom_id_custom_material_types_material_type_id_fk" FOREIGN KEY ("material_type_custom_id") REFERENCES "public"."custom_material_types"("material_type_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_unit_master_id_unit_master_unit_id_fk" FOREIGN KEY ("unit_master_id") REFERENCES "public"."unit_master"("unit_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "resource_transfers" ADD CONSTRAINT "resource_transfers_unit_custom_id_custom_units_unit_id_fk" FOREIGN KEY ("unit_custom_id") REFERENCES "public"."custom_units"("unit_id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sites" ADD CONSTRAINT "sites_supervisor_id_user_profiles_user_id_fk" FOREIGN KEY ("supervisor_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sites" ADD CONSTRAINT "sites_created_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("created_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sites" ADD CONSTRAINT "sites_updated_by_user_id_user_profiles_user_id_fk" FOREIGN KEY ("updated_by_user_id") REFERENCES "public"."user_profiles"("user_id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "subcategories" ADD CONSTRAINT "subcategories_category_id_categories_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("category_id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "notifications_user_id_unread_idx" ON "notifications" USING btree ("user_id","read_at") WHERE "notifications"."read_at" is null;--> statement-breakpoint
CREATE INDEX "resource_requests_site_id_idx" ON "resource_requests" USING btree ("site_id");--> statement-breakpoint
CREATE INDEX "resource_requests_status_idx" ON "resource_requests" USING btree ("status");--> statement-breakpoint
CREATE INDEX "resource_transfers_status_idx" ON "resource_transfers" USING btree ("status");--> statement-breakpoint
CREATE INDEX "resource_transfers_from_site_id_idx" ON "resource_transfers" USING btree ("from_site_id");--> statement-breakpoint
CREATE INDEX "resource_transfers_to_site_id_idx" ON "resource_transfers" USING btree ("to_site_id");